version: "3.9"
services:
    express:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/usr/src
            - /usr/src/node_modules
        links:
            - "redis"
        ports:
            - "3001:3001"
    redis:
        image: "redis"
