@url = http://localhost:3001

###

GET {{url}}/

###

// Turn on motor 3
POST {{url}}/motors?id=3&action=1

###

// Shutdown drone
POST {{url}}/drone?action=0

###

// Startup drone
POST {{url}}/drone/on
